### ISSUE TITLE
How to enable Presence in example 'gin_auth'

### ISSUE THREAD

**Issue by ethan2k** [centrifugal/centrifuge#152]
Could someone please explain to me how can I enable the Presence detection in the "gin_auth" example?
( https://github.com/centrifugal/centrifuge/tree/master/_examples/gin_auth )

Because when I run it, I get the following error: "Presence error: {"code":108,"message":"not available"}"

The file 'chat.html' contains the 'showPresence(sub)' method, which is meant to show how many people are present in the chat room. Running the example unmodified  I keep running into the error above and I'm wondering if I'm overlooking something obvious.

**Comment by FZambia** [comment]
Hello, first take a look at [ChannelOptionsFunc](https://godoc.org/github.com/centrifugal/centrifuge#ChannelOptionsFunc). By default all features for channels disabled in Centrifuge. That's because presence enabled for channel will cost additional resource usage on server. So it's a developer responsibility to decide in which channels to enable Presence.

You also need to define Presence handler on Node:

```go
node.OnPresence(func(c *centrifuge.Client, e centrifuge.PresenceEvent) (centrifuge.PresenceReply, error) {
	return centrifuge.PresenceReply{}, nil
})
```

In this handler you can theoretically check client permissions to call presence, maybe throttle those calls. 

See an example where [presence enabled for a channel](https://github.com/centrifugal/centrifuge/blob/3f1869a4321dffc91f4ebd480a0cdc2edaef154c/_examples/chat_json/main.go#L70). And [presence handler set](https://github.com/centrifugal/centrifuge/blob/3f1869a4321dffc91f4ebd480a0cdc2edaef154c/_examples/chat_json/main.go#L181).

**Comment by ethan2k** [comment]
Thank you so much for your quick and informative reply, I really appreciate it!

What you wrote really brought everything together and it's working wonderfully now. :) 

I had already looked at the ChannelOptions(Func) a bit, but I had overlooked the OnPresence handler for the Node instance..

Now I'm still figuring out GitHub and how to actually use it for collaboration a bit, but I've just forked centrifuge, modified the 'gin_auth' example by enabling presence (I think a chat room is a good situation to incorporate an example of how to use presence) and already committed it to my fork. If I understand correctly, I can create a pull request now so you can decide if you like the changes that I made. 

However you decide, I hope that you receive my attempt to make a small contribution as a token of appreciation for this wonderful library that you've created. Many thanks again!

**Comment by FZambia** [comment]
> Now I'm still figuring out GitHub and how to actually use it for collaboration a bit, but I've just forked centrifuge, modified the 'gin_auth' example by enabling presence (I think a chat room is a good situation to incorporate an example of how to use presence) and already committed it to my fork. If I understand correctly, I can create a pull request now so you can decide if you like the changes that I made.

Thanks man, but actually I prefer to just disable it in Gin auth example to let the example concentrate on its main goal – showing Gin integration rather than Centrifuge specific features.
