### ISSUE TITLE
Does it safe to put handleCommand in goroutine? (Manage client operations concurrency)

### ISSUE THREAD

**Issue by thanhps42** [centrifugal/centrifuge#163]
In https://github.com/centrifugal/centrifuge/blob/master/client.go#L651
![image](https://user-images.githubusercontent.com/11658963/95271969-77d57c00-0869-11eb-933a-00fb19804a20.png)

Can I put it in to goroutine? Because slow rpc command can effect to all of application. I think it need to put to goroutine.

P/s: sorry for my English. Thanks.

**Comment by FZambia** [comment]
Hello @thanhps42, great answer, I've already considered that but decided to wait for the real need from the library user before solving.

It needs some investigation to answer properly, the short answer is no – you can not simply add goroutine here since it can introduce data races and other side-effects, especially for subscribe operations.

I suppose the safest approach here would be running only some commands in goroutines (at least `connect` command should run sequentially, also `ping` command does not deserve its own goroutine) and limit the number of concurrent calls a single connection can do at the same moment.

Do you already have a situation where slow RPC results in visible application responsiveness degradation btw?

**Comment by thanhps42** [comment]
> Do you already have a situation where slow RPC results in visible application responsiveness degradation btw?
Yes I have, when I need to call to backend to make a few HTTP requests for fetch external resources (it take about 10 seconds).
This is not big problem, I can solve it by subscribe "result_channel" in frontend, then backend push the result to "result_channel" (no need to wait rpc task). But I think it will be better when I can direct return from rpc (cleaner than subscribe for many channel, just for get result from rpc).

**Comment by FZambia** [comment]
Thanks for the information, yes - approach with job ID should reduce the impact of too slow operations. But you are right – this is definitely should be addressed by the library, and it can give other benefits such as faster subscribe to many channels for example. 

There are two possible approaches:

1) Manage this fully inside the library – run goroutines and limit concurrency with some sort of bounded semaphore. This way API will stay the same but different concurrency for different operations will be hard to achieve. Though I think it will cover most cases. 

2) Change event handlers API a bit to leave concurrency management for a developer. This approach is the most flexible I suppose, but it will result in less idiomatic API since event handlers will look like this:

```go
// RPCReplyCB should be called as soon as RPC operation complete. 
type RPCReplyCB func(RPCReply, error)

node.OnRPC(func(c *Client, e RPCEvent, cb RPCReplyCB) {
    log.Printf("RPC from user: %s, data: %s, method: %s", c.UserID(), string(e.Data), e.Method)
    go func() {
        // Manage concurrency on application level.
        time.Sleep(5 * time.Second)
        RPCReplyCB(RPCReply{Data: []byte(`{}`)}, nil)
    }()
})
```

This will allow users to use their own pools and concurrency limiting strategies (for example based on different RPC methods) but makes API more complicated.

Will try to evaluate both approaches – which way you personally prefer more @thanhps42 ?

**Comment by thanhps42** [comment]
I think 2 is better. The API is less idiomatic but still acceptable (and readable). I can manage goroutines in my way (such as using panjf2000/ants to manage gouroutines; or add to queue and process later...).

**Comment by FZambia** [comment]
Thanks, I suppose there will be other concerns as soon as I start prototyping a solution. Will add you to pull request if you dont mind, this will take some time though since changes are not very trivial.

**Comment by FZambia** [comment]
@thanhps42 hello, please take a look at #164

**Comment by FZambia** [comment]
Merged changes in master, planning to release v0.13.0 tomorrow. [Changelog](https://github.com/centrifugal/centrifuge/blob/master/changelog.md#v0130)

**Comment by FZambia** [comment]
@thanhps42 thanks for opening this issue, it required more refactoring than I originally supposed. And looking at API changes in v0.13.0 (just released) it's a good thing to fix as early as possible.

**Comment by thanhps42** [comment]
> @thanhps42 thanks for opening this issue, it required more refactoring than I originally supposed. And looking at API changes in v0.13.0 (just released) it's a good thing to fix as early as possible.

Not at all. Thanks for your support (y).
