### ISSUE TITLE
How to use protobuf bytes publish

### ISSUE THREAD

**Issue by godtoy** [centrifugal/centrifuge#202]
thanks all guys.

![image](https://user-images.githubusercontent.com/13638996/129713772-fece7232-9c22-43cb-8088-60c6b42c0994.png)

when im try to publish a protobuf data
json: error calling MarshalJSON for type protocol.Raw: invalid character '$' looking for beginning of value /

**Comment by godtoy** [comment]
oh,i know what should i do.
I need to force the format=protobuf parameter option on the client, but at the moment I'm sending via bytes and don't quite understand why the serialisation of bytes would be detected.

**Comment by godtoy** [comment]
Unless the data in publish is reflective so that the client's format makes sense

**Comment by godtoy** [comment]
OK, I get it, if it's a json format, the raw data must not contain the binary data of the protobuf.This is a json serialization problem
![image](https://user-images.githubusercontent.com/13638996/129716396-cd2e7252-6ffa-4492-9d7d-002ff471d1d3.png)

![image](https://user-images.githubusercontent.com/13638996/129716612-196856d6-8b32-49bf-b8f3-ed93754c7a2b.png)

**Comment by godtoy** [comment]
![image](https://user-images.githubusercontent.com/13638996/129717107-e5dd2be3-1e94-4d29-afa7-27eb9f69112b.png)
And I think that when a single client fails to send, it should not return an error directly, but use continue to prevent other clients from not receiving the message due to problems with a single client, and serialized messages can be cached

**Comment by FZambia** [comment]
Hello!

If you have clients which are using JSON-based protocol connection then you can't send binary data to them - that's why you got `json: error calling MarshalJSON`. To communicate in binary format use clients with Protobuf protocol. I don't really see the full stack you are using from your comments so can't suggest concrete steps.

> And I think that when a single client fails to send, it should not return an error directly, but use continue to prevent other clients from not receiving the message due to problems with a single client, and serialized messages can be cached

It's already cached and the error will be returned only if message can't be serialized - there is no individual client involved at this point - just follow the code more carefully, it already does what you want I believe.

**Comment by godtoy** [comment]
thanks, i got it.
