### ISSUE TITLE
Token can' be generated

### ISSUE THREAD

**Issue by yagobski** [centrifugal/centrifuge#70]
Hi, 

I installed centrifuge all is fine but with my client i try to create the token but it is not connecting i have : invalid token error. 

Can you please tell me if this methods is good to generate token : 

$ctx = hash_init("md5", HASH_HMAC, $secret_key);
	hash_update($ctx, $project);
	hash_update($ctx, $userId.$timestamp);
	$token = hash_final($ctx);

OR 

$token = hash_hmac('md5', $project . $userId . $timestamp, $secret_key);

Thanks in advance
Regards

**Comment by FZambia** [comment]
Hello!

```
$ctx = hash_init("md5", HASH_HMAC, $secret_key);
hash_update($ctx, $project);
hash_update($ctx, $userId.$timestamp);
$token = hash_final($ctx);
```

Seems correct.

Maybe you are also sending custom `info`? Could you show centrifuge javascript object initialization?

Which versions of Centrifuge and Centrifuge-js do you use?

Also I suggest using sha256 instead of md5

Btw Centrifuge is currently moving to Go language - I am planning to release first version 25 May. [This](http://fzambia.gitbooks.io/centrifugal/content/) is a new documentation for the entire stack.

**Comment by FZambia** [comment]
Oh sorry, this is because empty info must present in token generation: https://github.com/centrifugal/cent/blob/master/cent/core.py#L37

So something like this should do the work:

```
$ctx = hash_init("md5", HASH_HMAC, $secret_key);
hash_update($ctx, $project);
hash_update($ctx, $userId.$timestamp);
hash_update($ctx, "{}")
$token = hash_final($ctx);
```
I see now that empty info is not so obvious when using your own function for token generation. I'll think about better way.

Please, try this

**Comment by FZambia** [comment]
I'll try to change default empty info from `"{}"` to just an empty string `""` in next release and in new Go version - so it won't affect token if not set.

**Comment by yagobski** [comment]
Thanks a lot it fix my problem. 
Why you rewrite all with Go language?
With new features we will get with your new release?

**Comment by FZambia** [comment]
You are welcome! I've made changes - `info` in Centrifuge 0.8.0 and in Go version will be empty string by default.

The reasons of moving to Go:
* perfomance (up to 20 times faster in my comparisons)
* run one process on several cores - no need to launch several Tornado processes
* easy to distribute (single executable file)
* Go's built-in concurrency - we can use all available libraries to make a product, no need to search for asynchronous non-blocking modules
